services:

  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_DATABASE: sunshine
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ${VOLUME_ROOT}/mysql/data:/var/lib/mysql
      - ${VOLUME_ROOT}/mysql/log:/var/log/mysql

  sunshine-ss:
    container_name: sunshine-ss
    hostname: jboss
    image: sunshine-ss:latest
    restart: always
    environment:
      MYSQL_HOST: mysql
      APP_IS_TEST_MODE: false
    ports:
      - 8787:8787
      - 8080:8080
      - 3300:3300
      - 9100:9100
    depends_on:
      - mysql
      - kafka
    volumes:
      - ${VOLUME_ROOT}/sunshine-ss-logs:/opt/logs

  sunshine-sch:
    container_name: sunshine-sch
    hostname: jboss
    image: sunshine-sch:latest
    restart: always
    ports:
      - 9787:8787
      - 9110:9110
    depends_on:
      - mysql
      - kafka
    volumes:
      - ${VOLUME_ROOT}/sunshine-sch-logs:/opt/logs



  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - sunshine-ss
      - sunshine-sch
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ${VOLUME_ROOT}/prometheus:/etc/prometheus
      - ${VOLUME_ROOT}/prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ${VOLUME_ROOT}/grafana:/etc/grafana/provisioning/datasources
